apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: docker.io/jkulrativ/sds-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 3

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      labels:
        app: gateway-app
    spec:
      containers:
      - name: gateway-app
        image: docker.io/jkulrativ/sds-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 3
        env:
        - name: chef_url
          value: "http://chef-service:50001"
        - name: recipe_url
          value: "http://recipe-service:50001"
        - name: review_url
          value: "http://review-service:50001"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chef-deployment
  labels:
    app: chef-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chef-app
  template:
    metadata:
      labels:
        app: chef-app
    spec:
      containers:
      - name: chef-app
        image: docker.io/polapob/chef-service:1.0-linux-arm64
        imagePullPolicy: Always
        ports:
        - containerPort: 50001
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 50001
          initialDelaySeconds: 15
          periodSeconds: 3

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-deployment
  labels:
    app: recipe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-app
  template:
    metadata:
      labels:
        app: recipe-app
    spec:
      containers:
      - name: recipe-app
        image: docker.io/polapob/recipe-service:1.0-linux-arm64
        imagePullPolicy: Always
        ports:
        - containerPort: 50002
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 50002
          initialDelaySeconds: 15
          periodSeconds: 3

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-deployment
  labels:
    app: review-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-app
  template:
    metadata:
      labels:
        app: review-app
    spec:
      containers:
      - name: review-app
        image: docker.io/polapob/review-service:1.0-linux-arm64
        imagePullPolicy: Always
        ports:
        - containerPort: 50003
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 50003
          initialDelaySeconds: 15
          periodSeconds: 3
