apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: chef-service
spec:
  selector:
    app: chef-app
  ports:
    - protocol: TCP
      port: 50001
      targetPort: 50001

---

apiVersion: v1
kind: Service
metadata:
  name: recipe-service
spec:
  selector:
    app: recipe-app
  ports:
    - protocol: TCP
      port: 50002
      targetPort: 50002

---

apiVersion: v1
kind: Service
metadata:
  name: review-service
spec:
  selector:
    app: review-app
  ports:
    - protocol: TCP
      port: 50003
      targetPort: 50003
